"""empty message

Revision ID: bd7a8af0cc3f
Revises: 
Create Date: 2018-11-13 07:58:32.377493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7a8af0cc3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('application', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_table('battery',
    sa.Column('b_id', sa.Integer(), nullable=False),
    sa.Column('cells', sa.Integer(), nullable=False),
    sa.Column('power', sa.String(length=32), nullable=False),
    sa.Column('life', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('b_id')
    )
    op.create_table('display',
    sa.Column('d_id', sa.Integer(), nullable=False),
    sa.Column('dstyle', sa.String(length=32), nullable=False),
    sa.Column('dtype', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('d_id')
    )
    op.create_table('graphics',
    sa.Column('g_id', sa.Integer(), nullable=False),
    sa.Column('gName', sa.String(length=32), nullable=False),
    sa.Column('gType', sa.String(length=32), nullable=False),
    sa.Column('gMemory', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('g_id')
    )
    op.create_table('memory',
    sa.Column('mem_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.String(length=15), nullable=False),
    sa.Column('ram', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('ssd', sa.String(length=20), nullable=True),
    sa.Column('rpm', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('mem_id')
    )
    op.create_table('processor',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('proName', sa.String(length=32), nullable=False),
    sa.Column('proType', sa.String(length=32), nullable=False),
    sa.Column('speed', sa.String(length=32), nullable=False),
    sa.Column('noCores', sa.String(length=32), nullable=False),
    sa.Column('bit', sa.Integer(), nullable=False),
    sa.Column('gen', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pro_id')
    )
    op.create_table('trigger_delete',
    sa.Column('td_id', sa.Integer(), nullable=False),
    sa.Column('userDelete', sa.String(length=32), nullable=False),
    sa.Column('modelNo', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('td_id')
    )
    op.create_table('trigger_insert',
    sa.Column('ti_id', sa.Integer(), nullable=False),
    sa.Column('userInsert', sa.String(length=32), nullable=False),
    sa.Column('modelNo', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('ti_id')
    )
    op.create_table('trigger_update',
    sa.Column('tu_id', sa.Integer(), nullable=False),
    sa.Column('userUpdate', sa.String(length=32), nullable=False),
    sa.Column('modelNo', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('tu_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=63), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lap_mod',
    sa.Column('model_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=False),
    sa.Column('image_file', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, asdecimal=False), nullable=False),
    sa.Column('dimensions', sa.String(length=64), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('warranty', sa.String(length=32), nullable=False),
    sa.Column('ratings', sa.Numeric(precision=8, asdecimal=False), nullable=False),
    sa.Column('price', sa.String(length=32), nullable=False),
    sa.Column('proc_id', sa.Integer(), nullable=True),
    sa.Column('memo_id', sa.Integer(), nullable=True),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('did', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['battery.b_id'], ),
    sa.ForeignKeyConstraint(['did'], ['display.d_id'], ),
    sa.ForeignKeyConstraint(['gid'], ['graphics.g_id'], ),
    sa.ForeignKeyConstraint(['memo_id'], ['memory.mem_id'], ),
    sa.ForeignKeyConstraint(['proc_id'], ['processor.pro_id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('application',
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('a_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a_id'], ['applications.a_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['lap_mod.model_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('lap_mod')
    op.drop_table('user')
    op.drop_table('trigger_update')
    op.drop_table('trigger_insert')
    op.drop_table('trigger_delete')
    op.drop_table('processor')
    op.drop_table('memory')
    op.drop_table('graphics')
    op.drop_table('display')
    op.drop_table('battery')
    op.drop_table('applications')
    # ### end Alembic commands ###
